version: '3.1'

services:
  app:
    container_name: app
    image: mindy
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    networks: 
      - mongo-compose-network

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks: 
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge